theme: jekyll-theme-minimal
title: Fabian Leon
description: My working portfolio
#### Support or Contact
[Google Scholar](https://scholar.google.com/citations?user=RCa1vLoAAAAJ&hl=en)  
[LinkedIn](https://www.linkedin.com/in/fabian-leon-019a44111/)  
[Twitter](https://twitter.com/QuantumPhabian)   
[Texas A&M SCSC](https://soilcrop.tamu.edu/people/leon-fabian/)
