theme: jekyll-theme-minimal
title: Fabian Leon
description: My working portfolio in sorghum and genetics

Email:  fabian.leon@tamu.edu  
Twitter: [quantumphabian](https://twitter.com/QuantumPhabian)  
Google Scholar: [Fabian Leon](https://scholar.google.com/citations?user=RCa1vLoAAAAJ&hl=en)  
LinkedIn: [Fabian Leon](https://www.linkedin.com/in/fabian-leon-019a44111/)   
Github: [leon-fabian](https://github.com/leon-fabian)
